config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  post '/oauth_email_confirmation', to: 'users#oauth_email_confirmation'

  get '/search', to: 'searches#search'

  concern :votable do
    member do
      patch :upvote
      patch :downvote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :answers, shallow: true, only: %i[create destroy update], concerns: [:votable] do
      resources :comments, shallow: true, only: %i[create]
      member do
        post :best
      end
    end

    resources :comments, shallow: true, only: %i[create]

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :badges, only: %i[index]
  scope :active_storage, module: :active_storage, as: :active_storage do
    resources :attachments, only: %i[destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create destroy edit update] do
        resources :answers, only: %i[index show create destroy edit update], shallow: true
      end
    end
  end

  resources :users, only: %i[show]

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable, inverse_of: :linkable
  has_one :badge, dependent: :destroy
  belongs_to :user
  has_many :subscriptions, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  has_many_attached :files

  validates :title, :body, presence: true
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  skip_before_action :verify_authenticity_token, only: %i[create destroy]
  skip_authorization_check only: [:destroy]

  def index
    authorize! :read, Question
    @questions = Question.all
    render json: @questions, adapter: :json
  end

  def show
    authorize! :read, Question
    @question = Question.find(params[:id])
    render json: @question, adapter: :json
  end

  def create
    authorize! :create, Question
    @question = current_resource_owner.questions.new(question_params)

    respond_to do |format|
      format.json do
        if @question.save
          render json: @question, adapter: :json, status: :created
        else
          render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    authorize! :destroy, @question
    respond_to do |format|
      format.json do
        @question.destroy
        render json: { message: 'Question deleted' }, status: :ok
      end
    end
  end

  def edit
    @question = Question.find(params[:id])
    authorize! :update, @question
    render json: @question, adapter: :json
  end

  def update
    @question = Question.find(params[:id])
    authorize! :update, @question
    if @question.update(question_params)
      render json: @question, adapter: :json
    else
      render json: { error: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def question_params
    if action_name == 'create'
      params.require(:question).permit(:title, :body, links_attributes: %i[id name url _destroy],
                                                      badge_attributes: %i[name icon])
    else
      params.require(:question).permit(:title, :body, links_attributes: %i[id name url _destroy])
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  skip_before_action :authenticate_user!, only: %i[index show]

  after_action :publish_question, only: %i[create]

  def index
    authorize! :read, Question
    @questions = Question.all
  end

  def show
    authorize! :read, Question
    @answer = question.answers.new
    @answer.links.build
    @subscription = question.subscriptions.where(user: current_user).first
  end

  def new
    authorize! :create, Question
    question.links.build
    Badge.new(question: question)
  end

  def create
    authorize! :create, Question
    @question = current_user.questions.new(question_params)

    if @question.save
      question.subscriptions.create(user: current_user)
      redirect_to @question, notice: 'Question successfully created!'
    else
      render :new
    end
  end

  def update
    authorize! :update, question
    question.update(question_params)
    question.files.attach(params[:question][:files]) if params[:question][:files]
  end

  def destroy
    authorize! :destroy, question
    question.comments.destroy_all
    question.destroy
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  helper_method :question

  def question_params
    if action_name == 'create'
      params.require(:question).permit(:title, :body, files: [],
                                                      links_attributes: %i[id name url _destroy],
                                                      badge_attributes: %i[name icon])
    else
      params.require(:question).permit(:title, :body, links_attributes: %i[id name url _destroy])
    end
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast 'questions', @question
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: question, local: true do |form|
  .form-question
    .form-group.row
      .col-12.col-md-1
        = form.label :title, class: 'col-form-label'
      .col-12.col-md-11
        = form.text_field :title, class: 'form-control', placeholder: 'Question title'
    .form-group.row
      .col-12.col-md-1
        = form.label :body, class: 'col-form-label'
      .col-12.col-md-11
        = form.text_area :body, class: 'form-control', rows: 3, placeholder: 'Ask question'
    .form-group.row
      .col-12.col-md-1
        = form.label :files, class: 'col-form-label'
      .col-12.col-md-11
        = form.file_field :files, multiple: true, direct_upload: true
    .bg-light.p-3.my-2
      p Links:
      #links
        = form.fields_for :links do |link|
          = render 'link_fields', f: link
        .links
          = link_to_add_association 'add link', form, :links
    .bg-light.p-3.my-2
      p Badge:
      = form.fields_for :badge do |badge|
        .form-group.row
          .col-12.col-md-2
            = badge.label :name, 'Badge name', class: 'col-form-label'
          .col-12.col-md-10
            = badge.text_field :name, class: 'form-control'
        .input-group
          .input-group-prepend
            span class="input-group-text" Icon
          .custom-file
            = badge.file_field :icon, class: 'custom-file-input'
            = badge.label :icon, 'Choose', class: 'custom-file-label'

  p = form.submit class: 'btn btn-primary'

app/views/questions/_link_fields.html.slim
.nested-fields
  .form-group.row
    .col-12.col-md-2
      = f.label :name, 'Link name', class: 'col-form-label'
    .col-12.col-md-10
      = f.text_field :name, class: 'form-control'
  .form-group.row
    .col-12.col-md-2
      = f.label :url, class: 'col-form-label'
    .col-12.col-md-10
      =f.text_field :url, class: 'form-control'
  = link_to_remove_association 'remove link', f

app/views/questions/_question.html.slim
.row.question-summary id="question-#{question.id}"
  .col-12.col-md-8
    = link_to question.title, question_path(question), class: 'question-link', id: question.id
  .question-asked.col-12.col-md-4
    = "asked #{question.created_at}"
  .question-delete.col-12
    - if can?(:destroy, question)
      = link_to 'Delete', question_path(question),
              method: :delete,
              class: 'text-danger',
              data: {remote: true}

app/views/questions/destroy.js.erb
$('#question-' + <%= question.id %>).remove()
$('.notice').html("Question deleted successfully")

app/views/questions/index.html.slim
.container.questions
  .row
    .col-12.col-md-9
      p class="questions-header" Questions:
    .col-12.col-md-3 = link_to 'Ask question', new_question_path, class: 'ask-button'


  = render @questions

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

.container.mt-3

  h1 Create new question

  = render 'form'

app/views/questions/show.html.slim
.container.question
  .row
    - cache ['title_for', question] do
      .col-12.col-md-8
        h2 class="question-title" = question.title
    - if can? :edit, question
      .col-12.col-md-4
        .d-flex.flex-row-reverse
          = link_to 'Edit question', '#', class: 'ask-button edit-question'
  - cache ['when_asked', question] do
  .row
    .col
      p class="question-asked"
        = "Asked #{question.created_at}"

  hr

  .row
    - cache ['body_for', question] do
      .col-12.col-md-10
        h4 class="question-body" = question.body
        .question-files
          - if question.files.attached?
            = render 'shared/files', resource: question
    .rating.col-12.col-md-2
      table align="right"
        tr
          - unless can? :edit, question
            td
              h2 class="question-upvote"
                = link_to "\u2B06", upvote_question_path,
                        id: "upvote-question",
                        method: :patch,
                        remote: true,
                        data: {format: :json}
        tr
          td align="center"
            h2 class="question-rating-counter" = question.votes.sum(:useful)
        tr
          - unless can? :edit, question
            td
              h2 class="question-downvote"
                = link_to "\u2B07", downvote_question_path,
                        id: "downvote-question",
                        method: :patch,
                        remote: true,
                        data: {type: :json}

  .subscription
    - if @subscription
      - if can? :destroy, @subscription
        = link_to 'Unsubscribe',
                subscription_path(@subscription),
                method: :delete,
                remote: true,
                id: 'unsubscribe-from-answers',
                class: 'btn btn-primary'
        = link_to 'Subscribe',
                question_subscriptions_path(question),
                method: :post,
                remote: true,
                id: 'subscribe-for-answers',
                class: 'btn btn-primary hidden'
    - else
      - if can?(:create, Subscription)
        = link_to 'Subscribe',
                question_subscriptions_path(question),
                method: :post,
                remote: true,
                id: 'subscribe-for-answers',
                class: 'btn btn-primary'
        = link_to 'Unsubscribe', '#',
                method: :delete,
                remote: true,
                id: 'unsubscribe-from-answers',
                class: 'btn btn-primary hidden'

  - cache ['links_for', question] do
    .question-links
      p Links
      ul
        = render question.links


  .question-errors
  = form_with model: question, class: 'hidden question-edit-form' do |form|
    .form-question
      .form-group.row
        .col-12.col-md-1
          = form.label :title, class: 'col-form-label'
        .col-12.col-md-11
          = form.text_field :title, class: 'form-control', placeholder: 'Question title'
      .form-group.row
        .col-12.col-md-1
          = form.label :body, class: 'col-form-label'
        .col-12.col-md-11
          = form.text_area :body, class: 'form-control', rows: 3, placeholder: 'Ask question'
      .form-group.row
        .col-12.col-md-1
          = form.label :files, class: 'col-form-label'
        .col-12.col-md-11
          = form.file_field :files, multiple: true, direct_upload: true
      p Links:
      #links
        = form.fields_for :links do |link|
          = render 'link_fields', f: link
        .links
          = link_to_add_association 'add link', form, :links

      = form.submit class: 'btn btn-primary'

  - cache ['comments_for', question] do
    .question-comments
      p Comments:
      ul class="question-comments-list list-group"
        = render question.comments.persisted
      = render 'comments/form', commentable: question, comment: question.comments.new

  - cache ['answers_for', question] do
    .row
      .col
        h3 = "#{question.answers.count} Answers:"
    .answers
      = render question.answers.where(best: true)
      = render question.answers.where(best: false)

  = render 'answers/form', answer: question.answers.new

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: question %>')

<% if !question.errors.present? %>
  $('.question-title').html('<%= question.title %>')
  $('.question-body').html('<%= question.body %>')
  $('.question-files').html('<%= render 'shared/files', resource: question %>')
  $('.question-links').html('<%= render question.links %>')
  $('.question-edit-form').addClass('hidden')
  $('.edit-question').show()
<% end %>