config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  post '/oauth_email_confirmation', to: 'users#oauth_email_confirmation'

  get '/search', to: 'searches#search'

  concern :votable do
    member do
      patch :upvote
      patch :downvote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :answers, shallow: true, only: %i[create destroy update], concerns: [:votable] do
      resources :comments, shallow: true, only: %i[create]
      member do
        post :best
      end
    end

    resources :comments, shallow: true, only: %i[create]

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :badges, only: %i[index]
  scope :active_storage, module: :active_storage, as: :active_storage do
    resources :attachments, only: %i[destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create destroy edit update] do
        resources :answers, only: %i[index show create destroy edit update], shallow: true
      end
    end
  end

  resources :users, only: %i[show]

  mount ActionCable.server => '/cable'
end

app/views/shared/_delete_file_attached.js.erb
$('#file-' + <%= @file.id %>).remove()

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b = "#{resource&.errors.count} error(s) detected: "
  ul
  - resource&.errors.full_messages.each do |message|
    li class="text-danger" = message

app/views/shared/_files.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    .file id="file-#{file.id}"
      = link_to file.filename.to_s, url_for(file)
      - if current_user&.author_of?(file.record)
        = '  |  '
        = link_to 'Delete file', active_storage_attachment_path(file), method: :delete, data: { remote: true }

app/views/shared/_navbar.html.slim
nav class="navbar navbar-expand-lg navbar-light bg-light"
  = link_to 'Q&A', root_path, class: 'navbar-brand'
  - if user_signed_in?
    = link_to 'Achievements', badges_path, class: 'nav-link'
    = link_to 'Log out', destroy_user_session_path, class: 'nav-link', method: :delete
  - else
    = link_to 'Log in', new_user_session_path, class: 'nav-link'
  = form_with url: search_path, method: :get, local: true do |form|
    .form-row
      .col
        = form.text_field :query, class: 'form-control mr-sm-2', type: 'search'
      .col
        = form.collection_select :query_class,
                SearchesController::SEARCH_CLASSES,
                :constantize, :to_s,
                {prompt: 'Everywhere'},
                {class: 'form-control'}
      = form.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

app/views/shared/facebook_email.html.slim
h3 Just let us know your e-mail address to finish your sign up process

.errors
  = render 'shared/errors', resource: @user

= form_with url: oauth_email_confirmation_path, local: true do |form|
  = form.label :email
  = form.text_field :email
  = form.submit