config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  post '/oauth_email_confirmation', to: 'users#oauth_email_confirmation'

  get '/search', to: 'searches#search'

  concern :votable do
    member do
      patch :upvote
      patch :downvote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :answers, shallow: true, only: %i[create destroy update], concerns: [:votable] do
      resources :comments, shallow: true, only: %i[create]
      member do
        post :best
      end
    end

    resources :comments, shallow: true, only: %i[create]

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :badges, only: %i[index]
  scope :active_storage, module: :active_storage, as: :active_storage do
    resources :attachments, only: %i[destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create destroy edit update] do
        resources :answers, only: %i[index show create destroy edit update], shallow: true
      end
    end
  end

  resources :users, only: %i[show]

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable
  has_many :votes, as: :votable, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank

  has_many_attached :files

  validates :body, presence: true

  after_create :send_new_answer_notice

  def is_best!
    Answer.transaction do
      unless best
        question.answers.find_by(best: true)&.update!(best: false)
        update!(best: true)
        user.badges.push(question.badge) if question.badge
      end
    end
  end

  private

  def send_new_answer_notice
    NewAnswerNoticeJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!

  after_action :publish_answer, only: %i[create]

  def create
    authorize! :create, Answer
    @answer = question.answers.create(answer_params.merge(user: current_user))
  end

  def destroy
    authorize! :destroy, answer
    answer.comments.destroy_all
    answer.destroy
  end

  def update
    authorize! :update, answer
    answer.update(answer_params)
    answer.files.attach(params[:answer][:files])
  end

  def best
    @answer = Answer.find(params[:id])
    authorize! :best, answer
    @question = @answer.question
    @answer.is_best! if current_user&.author_of?(@question)
  end

  private

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new
  end

  helper_method :answer

  def question
    @question ||= Question.find(params[:question_id])
  end

  helper_method :question

  def answer_params
    if action_name == 'create'
      params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
    else
      params.require(:answer).permit(:body, links_attributes: %i[id name url _destroy])
    end
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast "answers-for-question-#{question.id}", @answer
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  skip_before_action :verify_authenticity_token, only: %i[create destroy]
  skip_authorization_check only: [:destroy]

  def index
    authorize! :read, Answer
    @answers = question.answers
    render json: @answers, adapter: :json, each_serializer: ListAnswerSerializer
  end

  def show
    authorize! :read, Answer
    @answer = Answer.find(params[:id])
    render json: @answer, adapter: :json
  end

  def create
    authorize! :create, Answer
    @answer = question.answers.new(answer_params.merge(user: current_resource_owner))

    respond_to do |format|
      format.json do
        if @answer.save
          render json: @answer, adapter: :json, status: :created
        else
          render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    authorize! :destroy, @answer
    respond_to do |format|
      format.json do
        @answer.destroy
        render json: { message: 'Answer deleted' }, status: :ok
      end
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    authorize! :update, @answer
    render json: @answer, adapter: :json
  end

  def update
    @answer = Answer.find(params[:id])
    authorize! :update, @answer
    if @answer.update(answer_params)
      render json: @answer, adapter: :json
    else
      render json: { error: @answer.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer_params
    if action_name == 'create'
      params.require(:answer).permit(:body, links_attributes: %i[name url])
    else
      params.require(:answer).permit(:body, links_attributes: %i[id name url _destroy])
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_search_path(answer)
    "/questions/#{answer.question_id}#answer-#{answer.id}"
  end
end

app/views/answers/_answer.html.slim
.answer
  - if answer.persisted?
    .row id="answer-#{answer.id}"
      .rating.col-12.col-md-2
        table align="right"
          tr
            - unless can? :edit, answer
              td
                h2 class="answer-upvote"
                  = link_to "\u2B06", upvote_answer_path(answer),
                          class: "upvote-answer",
                          method: :patch,
                          remote: true,
                          data: {format: :json, answer_id: answer.id}
          - cache ['rating_for', answer] do
            tr
              td align="center"
                = content_tag :h2, answer.votes.sum(:useful), class: "answer-#{answer.id}-rating-counter"
          tr
            - unless can? :edit, answer
              td
                h2 class="answer-downvote"
                  = link_to "\u2B07", downvote_answer_path(answer),
                          class: "downvote-answer",
                          method: :patch,
                          remote: true,
                          data: {type: :json, answer_id: answer.id}
      - cache ['body_for', answer] do
        .col-12.col-md-8
          p = answer.body
      .col-12.col-md-2
        - if can? :edit, (answer.question)
          = link_to 'Best', best_answer_path(answer),
                  method: :post, data: {remote: true},
                  class: answer.best ? 'btn best btn-success' : 'btn best btn-secondary'
      - cache ['links_for', answer] do
        .links.col-12
          p Links
          ul
            = render answer.links
      .col-12.answer-files
        = render 'shared/files', resource: answer
      .col-12
        - if can? :update, answer
          = 'Options: '
          = link_to 'Delete', answer_path(answer),
                  method: :delete,
                  data: {remote: true},
                  class: 'delete-answer'
        - if can? :destroy, answer
          = " | "
          = link_to 'Edit', '#',
                  class: "edit-answer-link",
                  data: {answer_id: answer.id}
        - cache ['edit_form_for', answer] do
          = form_with model: answer, class: 'hidden', html: {id: "edit-answer-#{answer.id}"} do |form|
            p = form.text_field :body
            p = form.file_field :files, multiple: true
            p Links:
            #links
              = form.fields_for :links do |link|
                = render 'link_fields', f: link
              .links
                = link_to_add_association 'add link', form, :links
            p = form.submit 'Save'
      .col-12

      - cache ['comments_for', answer] do
        .col-12.comments
          p Comments:
          ul class="answer-comments-list list-group"
            = render answer.comments.persisted
          = render 'comments/form', commentable: answer, comment: answer.comments.new

        hr

app/views/answers/_form.html.slim
= form_with model: [question, @answer], class: 'new-answer' do |form|
  .form-answer id="new_answer_form"
    .answer-errors
      = render 'shared/errors', resource: @answer
    .form-group.row
      .col-12
        = form.text_area :body, rows: 6, class: 'form-control'
    .form-group.row
      .col-12
        = form.file_field :files, multiple: true
    p Links:
    #links
      = form.fields_for :links do |link|
        = render 'link_fields', f: link
      .links
        = link_to_add_association 'add link', form, :links
    p = form.submit class: 'btn btn-primary'

app/views/answers/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    br
    = f.text_field :name
  .field
    = f.label :url
    br
    =f.text_field :url
  = link_to_remove_association 'remove link', f

app/views/answers/best.js.erb
$('.best').removeClass('btn-success').addClass('btn-secondary')
$('#answer-' + <%= @answer.id %> + ' .best').removeClass('btn-secondary').addClass('btn-success')

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>')

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>')
  $('.new-answer #answer_body').val('')
  $('input').val('')
<% end %>

app/views/answers/destroy.js.erb
$('#answer-' + <%= answer.id %>).remove()

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>')

<% if !answer.errors.present? %>
$('#answer-' + <%= answer.id %>).replaceWith('<%= j render answer %>')
<% end %>